runtime: python
service: default
env: flex
entrypoint: gunicorn -b :$PORT main:app --graceful-timeout 900 --timeout 900 --log-level=DEBUG



runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

skip_files:
- tests/